rotty/lexpr-rs

.travis.yml, Cargo.toml, benches/bench.rs, src/tests.rs
This allows for running the benchmarks on stable, and thus we can also
use clippy from stable.
=> benches: Switch to criterion

src/number.rs, src/print.rs, src/tests.rs
This allows moving the code for the internal `write` method to where
it belongs.
=> Add `Number::visit` method

src/tests.rs
This should guard against the non-optimized reader working directly on
`io::Write` being broken.
=> tests: Add roundtrip check via I/O traits

lexpr/src/tests.rs, lexpr/src/value/from.rs, lexpr/src/value/mod.rs, serde-lexpr/src/value/ser.rs
As we do not expect frequent in-line modification of strings, symbols
and keywords, let's cut down the size of the `Value` type by using
`Box<str>` instead of `String`.
=> Optimize value representation

lexpr/src/parse/error.rs, lexpr/src/parse/mod.rs, lexpr/src/parse/read.rs
Emacs Lisp support is still missing, although the parser option is
present.
Note that the `ignore_str` functionality was unused and removed. It
only made sense in direct combination with serde, as an optimization
when ignoring values.
=> Switch from JSON to R6RS string syntax

lexpr/src/parse/error.rs, lexpr/src/parse/read.rs, lexpr/src/parse/tests.rs
In Lisps, generally only `"` and `\` need escaping; this seems to be
true of all of R6RS/R7RS, Emacs Lisp and Common Lisp.
=> Adjust rules regarding escaping in strings

lexpr-macros/src/generator.rs, lexpr/TODO.md, lexpr/src/lib.rs, lexpr/src/parse/error.rs, lexpr/src/parse/mod.rs, lexpr/src/parse/tests.rs, lexpr/src/print.rs, lexpr/src/tests.rs, lexpr/src/value/from.rs, lexpr/src/value/mod.rs, serde-lexpr/Cargo.toml, serde-lexpr/src/value/de.rs, serde-lexpr/src/value/ser.rs, serde-lexpr/tests/value-serde.rs
Parsing Emacs Lisp unibyte strings is missing, and will be added in
another commit.
=> Initial support for byte vectors

lexpr/README.md, lexpr/TODO.md, lexpr/src/lib.rs, lexpr/src/parse/error.rs, lexpr/src/parse/mod.rs, lexpr/src/parse/read.rs, lexpr/src/parse/tests.rs, lexpr/src/print.rs, lexpr/src/tests.rs, lexpr/src/value/from.rs, lexpr/src/value/mod.rs, lexpr/src/value/tests.rs, serde-lexpr/src/value/de.rs, serde-lexpr/src/value/ser.rs, serde-lexpr/tests/value-serde.rs
Emacs Lisp read syntax is not yet implemented; it will be added in a
later commit.
=> Initial support for characters

lexpr/src/parse/mod.rs, lexpr/src/parse/read.rs, lexpr/src/parse/tests.rs, lexpr/src/print.rs, lexpr/src/style.rs, lexpr/src/tests.rs, lexpr/tests/print-parse.rs
- This fixes the escaping for both R6RS and Emacs Lisp when printing;
it was still using unadapted code inherited from `serde-json`.
- The `CharEscape` enum now only contains the subset of memnonic
escapes understood by all of R6RS, R7RS and Emacs Lisp.
- Accept an escaped pipe, which is valid in both R6RS and R7RS.
=> Fix string escape syntax

.codecov.yml, .travis.yml, README.md, lexpr/Cargo.toml, lexpr/src/value/mod.rs, serde-lexpr/Cargo.toml, serde-lexpr/src/value/de.rs
- Run tests on Rust 1.32.0 as well, so we don't accidentially break
there.
- Run code coverage analysis using `cargo-tarpaulin` and codecov.io.
=> travis: Set up code coverage check

lexpr/src/parse/error.rs, serde-lexpr/src/error.rs
The standard library documentation on
`std::error::Error::description()` notes:
This method is soft-deprecated.
Although using it won’t cause compilation warning, new code should
use Display instead and new impls can omit it.
Thus let's just not implement it, as new code should not use it, and
any code using `lexpr` is by definition, given its youth, quite new.
=> Remove Error `description()` method implementations

.travis.yml
This provides documentation of the current master branch via github
pages, in addition to documentation of released versions on docs.rs.
=> travis: Publish current docs on github pages

README.md, lexpr/README.md, serde-lexpr/README.md
- Add links to master API docs.
- Reference `serde_yaml` from top-level README.
=> Tweak the README files a bit

lexpr-macros/src/lib.rs, lexpr/src/cons.rs, lexpr/src/lib.rs, lexpr/src/number.rs, lexpr/src/parse/error.rs, lexpr/src/parse/mod.rs, lexpr/src/value/mod.rs, serde-lexpr/src/error.rs, serde-lexpr/src/lib.rs
As pointed out by the clippy lint `needless-doctest-main`, this allows
for a bit more succinct examples.
=> Eliminate `main`-like functions from doctests

lexpr-macros/Cargo.toml, lexpr/Cargo.toml, lexpr/NEWS.md
This is accompanied by release 0.2.1 of the internal `lexpr-macros`
crate.
=> lexpr: Prepare for v0.2.4

.travis.yml
This seems more transparent than using a Docker image.
=> Travis CI: Install tarpaulin via crates.io

.gitignore, .travis.yml, lexpr-macros/src/lib.rs, lexpr/README.md, msrv-test/Cargo.toml, msrv-test/src/main.rs
Since our `dev-dependencies` now require a newer Rust version, no
longer do a full test for Rust 1.32.0.
=> Travis CI: For Rust 1.32.0, only do a compilation check

lexpr/NEWS.md, lexpr/src/parse/mod.rs, lexpr/src/parse/tests.rs, serde-lexpr/src/value/de.rs
The newly-understood syntax is based on R7RS, and is understood
unconditionally, although this is considered a bug; the elisp parser
options should preclude using this syntax, but there is no knob for
disabling this syntax yet.
=> Add support number radix prefixes

lexpr/README.md, lexpr/src/parse/mod.rs, lexpr/src/parse/tests.rs
- Hexadecimal, octal, and binary literals are now supported; these
luckily have the same syntax in Scheme and Emacs Lisp.
- The quoting syntactic shorthands are now supported.
=> Add support for quoting shorthands

lexpr-macros/src/parser.rs, lexpr/src/datum.rs, lexpr/src/parse/mod.rs, lexpr/src/parse/tests.rs
Due to the addition of the `Datum` API, the original `Parser` method
names, especially `parse`, are now suboptimal. This change, while not
breaking API, adds a bunch of deprecations and new names, as well as
an iteration API for `Datum` values:
- Instead of calling `parse`, it is advised to use the value iteration
API, available via `value_iter`. For `Datum`, there is its, also
newly-added `datum_iter` counterpart. The previously-public, but
never released, `parse_datum` method is now internal.
`parse_datum` and `parse` can be emulated by calling
`next().transpose()` on the respective iterators, but it is expected
they were used for iteration (e.g. via `while let`) in the first
place, and these iterations can now be written a bit more
idiomatically using a for loop:
```rust
for datum in …
```
=> lexpr: Make the `Parser` API more symmetric

lexpr/src/cons.rs, lexpr/src/value/mod.rs
This mirrors the `list_iter` method that was introduced with the
`Datum` API; it provides an ergonomic way to walk through a chain of
cons cells, while still allowing handling of dotted lists.
=> lexpr: Add `list_iter` method to `Value` and `Cons`

lexpr/src/parse/mod.rs
These are variants of the `expect_value` and `expect_datum` that do
not produce an error when encountering the end of input.
While using an iterator is the right approach for consuming a sequence
of S-expressions, consuming a single S-expression should be convenient
as well.
=> lexpr: Add `next_value` and `next_datum` parser methods

serde-lexpr/src/value/de.rs, serde-lexpr/tests/value-serde.rs
Hi.  Thanks for your sexpr work.
This small series fixes a serious bug, preventing deserialization of empty maps.  That's issue #60.  It also adds some test cases, including notably for `HashMap`.
NB there is one test case for the serialisation #() of an empty tuple struct, `struct Thing ( )`.  You might want to consider whether this is what you intended.  It seems logical to me, so I didn't make a commit to change it.
I already submitted an MR for that new test case commit - that's #61.  The first commit in that MR is in this MR too.  I hope this is OK with you and not too confusing.  If it's confusing, please close #61.
=> Fix serialization of empty map

lexpr/src/parse/tests.rs
This should ensure that we don't regress on the fix in commit 6e726ca.
=> Add test cases for symbol followed by closing bracket

serde-lexpr/src/value/de.rs, serde-lexpr/tests/value-serde.rs
Prior to this change, deserializing a cons cell via `deserialize_any` would always yield the `car` of the cell, not advancing to the `cdr`.
Kudos to @elidupree for reporting the issue and providing essentially complete code to test this.
Fixes #74.
=> serde-lexpr: Fix `ConsAccess`

lexpr-macros/Cargo.toml, lexpr/Cargo.toml, lexpr/NEWS.md, lexpr/README.md, serde-lexpr/Cargo.toml, serde-lexpr/NEWS.md, serde-lexpr/README.md
- Bump versions.
- Tighten inter-crate dependencies.
- Remove deprecated `badges` sections from `Cargo.toml` files.
=> Prepare for new release

lexpr/src/parse/mod.rs, lexpr/src/parse/tests.rs
Per the Racket [Reader documentation, section 1.3.2](https://docs.racket-lang.org/reference/reader.html), Racket allows symbols prefixed with `#%`, with the prefix included in the symbol. This change adds a new option that allows these symbols to be parsed correctly.
=> Implement parsing Racket-style #%-prefixed symbols

.github/workflows/CI.yml, Cargo.toml, README.md, lexpr-macros/Cargo.toml, lexpr-macros/src/parser.rs, lexpr/Cargo.toml, lexpr/README.md, lexpr/src/parse/mod.rs, lexpr/tests/print-parse.rs, msrv-test/Cargo.toml, serde-lexpr/Cargo.toml, serde-lexpr/README.md
Since the edition shipped with the Rust 1.56 toolchain, this also raises the MSRV to 1.56, which also is the first version to understand the `package.rust-version` setting, which is now present in all crates' `Cargo.toml` file.
=> Bump Rust edition to "2021"

serde-lexpr/src/value/ser.rs
=> serde-lexpr: Add comment notice why `to_value` is "by-value"

lexpr/src/parse/read.rs, lexpr/src/print.rs, serde-lexpr/src/value/ser.rs
clippy 0.1.78 no longer likes using multiple locations for trait bounds (lint `multiple_bound_locations`).
=> Fix clippy warnings

lexpr-macros/src/parser.rs, lexpr/NEWS.md, lexpr/src/lib.rs, lexpr/tests/sexp-macro.rs
Implementation by @samuel-jimenez in PR #96.
Duplicate of #96, closes #99.
=> Accept colon-prefixed keywords in `sexp` macro.

lexpr-macros/Cargo.toml, lexpr-macros/README.md, lexpr/Cargo.toml
The `lexpr` crate now also depends on the latest version, to make sure any mentioned features of the `sexp!` macro are actually present in the user-downloaded version of `lexpr-macros`.
=> Bump `lexpr-macros` version number

lexpr/NEWS.md, lexpr/README.md, lexpr/src/parse/mod.rs, lexpr/src/parse/tests.rs
Note that we may want to extend general symbol syntax support as well, on both parsing and printing, which is currently lacking (at least):
- R6RS/R7RS hex escapes
- R7RS pipe-quoted symbols
- Emacs Lisp escapes
=> Allow parsing numeric-looking symbols

lexpr-macros/Cargo.toml, lexpr/Cargo.toml
Version `0.2.3` was not yet released, so use that as version for the next release.
=> Revert accidental bump of `lexpr-macros` version

lexpr/NEWS.md, lexpr/src/cons.rs, lexpr/src/value/tests.rs
This avoids stack overflow when dropping long lists. Closes #104.
=> Add custom `Drop` implementation for `Cons`

lexpr/NEWS.md, lexpr/src/parse/mod.rs, lexpr/src/parse/read.rs, lexpr/src/tests.rs, lexpr/tests/print-parse.rs
=> lexpr: Symbols may start with any "alphabetic" unicode codepoint
